# Usa la imagen oficial de MySQL
FROM mysql:8.1.0

# Configura las variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=reserva_bd
ENV MYSQL_USER=usertest
ENV MYSQL_PASSWORD=usertest

# Exponer el puerto 3306
EXPOSE 3306